services:
  - type: web
    name: shopflow-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/shopflow-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8084
